# Path: /home/prrrssshhh/PROJECTS/primetrade.AI/src/main/resources/application.properties
spring.application.name=primetrade-api
server.port=8080
spring.datasource.url=jdbc:mysql://localhost:3306/primetrade_db
spring.datasource.username=root
spring.datasource.password=prashant.0927
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true
jwt.secret=primetrade_super_secret_jwt_key_PrashantBhanage_2024_very_long
jwt.expiration=604800000
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
